version: "3.9"
services:
  client_service:
    build:
      context: ./client_service
    container_name: client_service
    ports:
      - "8000:8000"
    env_file:
      - .env
    networks:
      - micro_net

  scheduler_service:
    build:
      context: ./scheduler_service
    container_name: scheduler_service
    depends_on:
      - client_service
    env_file:
      - .env
    networks:
      - micro_net

networks:
  micro_net:
    driver: bridge
